# Generated by Django 3.1.3 on 2020-11-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='broker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('company', models.TextField()),
            ],
            options={
                'db_table': 'broker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sqm', models.FloatField()),
                ('type', models.TextField()),
                ('soldprice', models.IntegerField(blank=True, null=True)),
                ('listprice', models.IntegerField()),
                ('soldyear', models.IntegerField(blank=True, null=True)),
                ('soldmonth', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('postalcode', models.IntegerField()),
                ('name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('council', models.TextField()),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
    ]
